name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Gatsby Site
        uses: jzweifel/gatsby-cli-github-action@master
        env:
          GATSBY_PROJECT_PATH: "./c19-malta-vis"
        with:
          gatsby-arg: build
      - name: Copy generated files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: c19-malta-vis/public
          remote: /home/covid19
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
          concurrency: 1
          recursive: true
