name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Gatsby Site
        uses: jzweifel/gatsby-cli-github-action@master
        env:
          GATSBY_PROJECT_PATH: "./website"
        with:
          gatsby-arg: build
      - name: Copy generated files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVKEY }}
          port: ${{ secrets.PORT }}
          source: "website/public"
          target: "/home/covid19"
          rm: true
