name: DailyDataUpdate

on:
  push:
    branches: [master]
  # schedule:
  #   - cron:  '0 13 * * *'

jobs:
  GenerateData:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
      with:
        ref: master
    - name: Setup Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Download Script
      run: |
        python download_latest.py
    - name: Execute Conversion Script
      run: |
        python convert_latest.py
    - name: Upload latest data
      uses: actions/upload-artifact@v2
      with:
        name: latest_data.json
        path: ./data/latest_data.json
  UpdateMaster:
    needs: [GenerateData]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Download latest data
      uses: actions/download-artifact@v2
      with:
        name: latest_data.json
    - name: Move downloaded artifact to folder
      run: |
        mv latest_data.json ./data/latest_data.json
    - name: Commit and Push updated data to master
    - run: |
        git config --global user.email "simon@agius-muscat.net"
        git config --global user.name "C19 Bot"
        git add ./data/latest_data.json
        git commit -am "Updated with data for date: `date +'%Y-%m-%d %H:%M:%S'`"
        git push
