name: DailyDataUpdate

on:
  push:
    branches: [master]
  # schedule:
  #   - cron:  '0 13 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
      with:
        ref: master
    - name: Setup Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Download Script
      run: |
        python download_latest.py
    - name: Execute Conversion Script
      run: |
        python convert_latest.py
    - name: Commit & Push latest data to master
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - run: |
        git config --global user.email "simon@agius-muscat.net"
        git config --global user.name "C19 Bot"
        git commit -am "Updated: `date +'%Y-%m-%d %H:%M:%S'`"
        git push
